import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

const BASE = '/soledad-devotion/';

/** Files copied verbatim from public/ — Rollup never sees them, so list them here. */
const PUBLIC_ASSETS = [
  'manifest.webmanifest',
  'icon-192.png',
  'icon-512.png',
  'icon-maskable-512.png',
  'apple-touch-icon.png',
  'favicon.svg',
];

function serviceWorkerSource(version: string, precache: string[]): string {
  return `// Generated by vite.config.ts — do not edit.
const CACHE = 'devotion-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL = '${BASE}';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  // App shell: cache first so a cold, offline launch still works.
  if (req.mode === 'navigate') {
    event.respondWith(caches.match(SHELL).then((hit) => hit || fetch(req)));
    return;
  }

  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }))
  );
});
`;
}

/** Emits dist/sw.js with a precache list built from whatever this build produced. */
function serviceWorker(): Plugin {
  let outDir = 'dist';
  return {
    name: 'devotion-service-worker',
    apply: 'build',
    configResolved(config) {
      outDir = join(config.root, config.build.outDir);
    },
    writeBundle(_options, bundle) {
      const emitted = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      const precache = [
        BASE,
        ...emitted.map((f) => BASE + f),
        ...PUBLIC_ASSETS.map((f) => BASE + f),
      ];
      const version = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
      writeFileSync(join(outDir, 'sw.js'), serviceWorkerSource(version, precache));
    },
  };
}

export default defineConfig({
  base: BASE,
  plugins: [serviceWorker()],
  build: {
    target: 'es2020',
    assetsInlineLimit: 4096,
  },
});
